### ISSUE TITLE
代码咨询

### ISSUE THREAD

**Issue by huahai2022** [CDM1619/Networked-MB-MARL#2]
After trainging, the actors model will be saved in checkpoints/xxx/Models/xxxbest_actor.pt, You just need to add following code in algorithms/algo/agent/DPPO.py(DMPO.py/CPPO.py/...):你好README中要在DMPO里面添加self._init_actors()，但是并没有这个函数

**Comment by CDM1619** [comment]
> After trainging, the actors model will be saved in checkpoints/xxx/Models/xxxbest_actor.pt, You just need to add following code in algorithms/algo/agent/DPPO.py(DMPO.py/CPPO.py/...):你好README中要在DMPO里面添加self._init_actors()，但是并没有这个函数

Thanks very much for your interest. In fact, you can see that the DMPOAgent class in the DMPO.py has already inherited DPPOAgent, so you only need to add your trained model in the initial part of the DMPOAgent: self.actors.load_state_dict(torch.load(test_actors_model)). The core meaning is that after initializing the actor model, you need to assign the trained model parameters to the already initialized model. If you have any questions that I can help you with, communicate with me anytime.

**Comment by huahai2022** [comment]
感谢，感谢
